ci: add exercise testing ci (#11)
Co-authored-by: Isaac Good <github@isaacgood.com>

diff --git a/bin/verify-exercises b/bin/verify-exercises
--- a/bin/verify-exercises
+++ b/bin/verify-exercises
@@ -19,17 +19,32 @@
 # ./bin/test
 
 # Verify the Concept Exercises
+failures=0
 for concept_exercise_dir in ./exercises/concept/*/; do
-    if [ -d $concept_exercise_dir ]; then
-        echo "Checking $(basename "${concept_exercise_dir}") exercise..."
-        # TODO: run command to verify that the exemplar solution passes the tests
+    if [ -d "$concept_exercise_dir" ]; then
+        slug=$(basename "${concept_exercise_dir}")
+        echo "Checking ${slug} exercise..."
+        mv "${concept_exercise_dir}/${slug}".sql "${concept_exercise_dir}/${slug}"_backup.sql
+        cp "${concept_exercise_dir}"/.meta/exemplar.sql "${concept_exercise_dir}/${slug}".sql
+        bin/verify-exercise-example "${slug}" "${concept_exercise_dir}" "${concept_exercise_dir}" || (( failures++ ))
+        mv -f "${concept_exercise_dir}/${slug}"_backup.sql "${concept_exercise_dir}/${slug}".sql
     fi
 done
 
 # Verify the Practice Exercises
 for practice_exercise_dir in ./exercises/practice/*/; do
-    if [ -d $practice_exercise_dir ]; then
-        echo "Checking $(basename "${practice_exercise_dir}") exercise..."
-        # TODO: run command to verify that the example solution passes the tests
+    if [[ -d "$practice_exercise_dir" ]]; then
+        slug=$(basename "${practice_exercise_dir}")
+        echo "Checking ${slug} exercise..."
+        mv "${practice_exercise_dir}/${slug}".sql "${practice_exercise_dir}/${slug}"_backup.sql
+        cp "${practice_exercise_dir}"/.meta/example.sql "${practice_exercise_dir}/${slug}".sql
+        ./bin/verify-exercise-example "${slug}" "${practice_exercise_dir}" "${practice_exercise_dir}" || (( failures++ ))
+        mv -f "${practice_exercise_dir}/${slug}"_backup.sql "${practice_exercise_dir}/${slug}".sql
     fi
 done
+
+if (( failures )); then
+    echo "${failures} tests failed!"
+    exit 1
+fi
+exit 0
