feat: more informative echo text

diff --git a/bin/verify-exercise-example b/bin/verify-exercise-example
--- a/bin/verify-exercise-example
+++ b/bin/verify-exercise-example
@@ -34,21 +34,21 @@ echo "${slug}: testing..."
 # stderr to capture it
 cd "${solution_dir}" || exit
 echo "${solution_dir}"
-test_output=$(sqlite3 '' --init "./${slug}_test.sql" -bail  '.exit' 2>&1)
-rm ./user_output.md || true
+test_output=$(sqlite3 '' --init "${slug}_test.sql" -bail  '.exit' 2>&1)
 
 # Check if sqlite ran withour errors:
 if [ $? -ne 0 ]; then
-    echo "Test failed for ${slug}"
+    echo "Test failed for ${slug} - sqlite3 error:"
     echo "${test_output}"
     exit 1
 fi
+rm ./user_output.md || true
 
 # check if all tests were succesfull
 failed_results=$(cat ./output.json | jq '.[] | select(.status=="fail") | {name, message}')
 rm ./output.json || true
-if [ -n "${failed_results}"]; then
-    echo "Test failed for ${slug}"
+if [ -n "${failed_results}" ]; then
+    echo "Test failed for ${slug} - failing tests:"
     echo "$failed_results"
     exit 1
 fi
